services:
  postgres:
    image: postgres
    container_name: pg_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres       # Set the username
      POSTGRES_PASSWORD: 123456 # Set the password
      POSTGRES_DB: university      # Set the database name
    volumes:
      - pg_data:/var/lib/postgresql/data # Persist data
      - ./db/init:/docker-entrypoint-initdb.d  # Initialization scripts

volumes:
  pg_data:
