# config.yaml
server:
  port: 8080

database:
  url: postgresql://postgres:123456@localhost:5432/university?sslmode=disable

cors:
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "*"
  expose_headers:
    - "*"
  allow_credentials: true

openai:
  api_key: ${OPENAI_API_KEY}

gemini:
  api_key: ${GEMINI_API_KEY}
  sandbox: true

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiry_hours: 24

serpapi:
  api_key: ${SERP_API_KEY}